Add ability to control mongo download
winfinit/mongodb-prebuilt pull request #51
Opened 2018-06-14 16:04 UTC by xscheiner

We needed to be able to download a specific version of mongo to run our tests. So we added the ability to pass in options that go to the mongodb-download package. We've tested that this runs cleanly in the default mode as well as with the options.

We also added some scripts for linting and building in package.json. We left in the fix option on the linting which has added a lot of spacing and formatting changes. Apologies for that.

2018-11-26 10:03 UTC, LoneRifle commented
Apologies, but could I have you redo this PR so that the linting and actual changes are in separate commits?

2018-11-26 12:49 UTC, LoneRifle requested changes
Per comments. If you could also split out the commit, that would be great

2018-11-26 12:49 UTC, LoneRifle commented on src/mongod-helper.ts
> +  }
This will not be needed as this has been implemented in #49

2018-12-01 03:50 UTC, LoneRifle approved these changes

2018-12-01 03:50 UTC, merged

2018-12-04 10:36 UTC, xscheiner commented
Sorry, I didn't see the notifications on these messages and I left you with a bit of extra work. Is it all sorted now?

2018-12-05 00:29 UTC, LoneRifle commented
Yes it is - published as 6.4.0. I had to force-push into your branch as part of the work done, sorry about that