Passing download parameters to bin commands through ENV variables
winfinit/mongodb-prebuilt pull request #55
Opened 2019-01-22 09:22 UTC by fedotov

Main goal of the pr is to set MongoDB version and download folder instead of latest version of MongoDB and home directory to download to use through bin commands.

Environment variables to set mongodb download parameters:
`mongodb_version`
`mongodb_downloadDir`
`mongodb_arch`
`mongodb_platform`

Example
`export mongodb_downloadDir='./' mongodb_version=3.4.10 && mongod --port 27018 --dbpath ./.mongodb/data --logpath /dev/stdout`

Also in pr:
* IMongoDBDownloadOpts replaced with Partial<IMongoDBDownloadOptions> from mongodb-download
* .editorconfig added
* .gitignore added .idea

2019-01-23 00:36 UTC, LoneRifle requested changes
A couple of points:
* I don't wish to have `.editorconfig` in this PR, since not everybody uses this. Can you remove this please?
* I will usually build the files myself, so please remove everything in `built/`
* I like that you have reused a mongodb-download class, but you are conflating this with the actual PR itself. At the very least, I would like two separate commits

2019-01-23 08:50 UTC, fedotov commented
Sure, will do.
Thanks for quick response

2019-01-24 01:26 UTC, LoneRifle commented
Apologies, one more comment - env vars are usually `ALL_CAPS_SNAKE_CASE`

2019-01-24 22:06 UTC, fedotov commented
@LoneRifle  please review

2019-01-25 01:19 UTC, LoneRifle approved these changes

2019-01-25 01:19 UTC, merged